[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  DB_TYPE = "mongodb"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  directory = ".netlify/functions/"

# Handle Next.js API routes and pages
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/__nextjs"
  status = 200

# Handle Next.js pages
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/__nextjs"
  status = 200 